# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airCheck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Toronto', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='Canada', max_length=20),
        ),
    ]
