# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airCheck', '0002_auto_20160423_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.CharField(default='30', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.CharField(default='-40', max_length=10),
        ),
    ]
